### ISSUE TITLE
Wrong use of CALTYPE_GREGORIAN

### ISSUE THREAD

**Issue by oliviermarti** [PBrockmann/ipython_ferretmagic#10]
In `datamethods.py,` line 531 and following : 

```
elif axis_types[k] == libpyferret.AXISTYPE_TIME:
            if not axis_units[k]:
                  axis_units[k] = CALTYPE_GREGORIAN
```

`CALTYPE_GREGORIAN` should probably be replaced by `libpyferret.CALTYPE_GREGORIAN`

Olivier

**Comment by PBrockmann** [comment]
Is it related to ferretmagic ?
Rather to pyferret.

**Comment by PBrockmann** [comment]
Not sure anyway there is any mistake.
Definitions are in pyfermod/pyferret.h and CALTYPE_GREGORIAN is correctly defined there
