### ISSUE TITLE
ferretmagic makes the kernel idle

### ISSUE THREAD

**Issue by singh-shikha** [PBrockmann/ipython_ferretmagic#12]
As soon as I load ferretmagic, the module loads. But at the very next line, the kernel becomes idle. This is a recent problem, it used to work before. And I am unable to figure out the conflict and reason of this behavior. Please help.

Runnig this on : Python 3.9.13

![image](https://user-images.githubusercontent.com/18552910/180987139-50ed67f4-8c00-4ca2-b973-3489023dab33.png)

**Comment by PBrockmann** [comment]
Indeed, same problem with Python 3.9.13
I am investigating

**Comment by PBrockmann** [comment]
It works if you install ipykernel at 6.9.2

```
conda install ipykernel=6.9.2
```

**Comment by PBrockmann** [comment]
Added a required argument cell_id=None needed by ipykernel 6.9.15

```
def run_cell_new(self, raw_cell, store_history=False, silent=False, shell_futures=True,  **kwargs):
```
-->
```
def run_cell_new(self, raw_cell, store_history=False, silent=False, shell_futures=True, cell_id=None, **kwargs):
```

Updated the pip package : https://pypi.org/project/ferretmagic/#history
Please do 
``` 
pip uninstall ferretmagic
pip install ferretmagic
```
