### ISSUE TITLE
is ferretmagic available with python3

### ISSUE THREAD

**Issue by goddarpb** [PBrockmann/ipython_ferretmagic#9]
Thanks,
Paul Goddard

**Comment by PBrockmann** [comment]
Hi,
I have just updated ferretmagic to run with python 3. It was just a matter of changing the print command call.
Please do
`pip uninstall ferretmagic`
then 
`pip install ferretmagic`

You should have the last 2018.9.28 release installed.
Then let me know.

**Comment by goddarpb** [comment]
Great, thanks so much Patrick. The package appears to be working order with Python3.6
Cheers,
Paul

**Comment by PBrockmann** [comment]
Could you please send me a capture ? I have a colleague that cannot run notebook with ferretmagic with a Mac OSX.

**Comment by goddarpb** [comment]
Here are some details of my computing setup.... please let me if there are other specifics you would like; I'm not sure what is meant by a capture :/

Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux

Name: pyferret
Version: 7.43

In general, I loaded anaconda3 and set up a python environment with the more popular data analysis packages.  Then, just yesterday, I added the newest version of pyferret with conda (conda 4.5.4):
conda install -c conda-forge pyferret 

Then, I followed your pip uninstall and pip install ferretmagic (pip 9.0.3, this version of pip was loaded when I installed pyferret)

Ferretmagic seems to work in the jupyter (v. 4.4.0) notebook with the python3 kernel.

**Comment by PBrockmann** [comment]
Cool thanks for this confirmation.
Yes a snapshot of your notebook (if possible) with some ferretmagic cells would be nice.
Happy ferreting with jupyter notebook !

**Comment by goddarpb** [comment]
Here are a few screenshots.  1st is the top of the notebook where I initiate ferretmagic and load data. Second shows moving variables between Ferret and python.  And third is a screen shot of a ferret-made figure with a pandas data frame with data initially made in ferret.
![1](https://user-images.githubusercontent.com/7451774/46224529-a0dee000-c324-11e8-9bfc-33a6a0983a7b.JPG)
![2](https://user-images.githubusercontent.com/7451774/46224537-a63c2a80-c324-11e8-9137-c7394095ccd1.JPG)
![3](https://user-images.githubusercontent.com/7451774/46224547-aa684800-c324-11e8-9818-4fdced9f4328.JPG)

**Comment by PBrockmann** [comment]
Cool. Many thank for sharing.
Patrick
